title: Project
# preset: page
pages: false
icon: 📖

fields:
  categories:
    label: Categorias
    type: checkboxes
    width: 1/4
    min: 1
    max: 3
    # columns: 2
    options:
      package: Design de embalagem
      book: Design de livro
      visualid: Identidade visual
      illustration: Ilustração
      lettering: Lettering
      mural: Pintura de mural
      personal: Projeto pessoal
  text:
    label: Texto
    type: textarea
    width: 3/4
    size: small
    required: true
  files:
    # width: 1/4
    label: Galeria
    layout: cards
    search: false
    required: true
    # size: tiny