title: Project
# preset: page
pages: false
icon: ✏️

columns:
  - width: 2/3
    sections:
      gallery:
        headline: Galeria
        type: files
        layout: cards
        template: image
        info: "{{ file.dimensions }}"
        min: 1
        size: small
        image:
          ratio: 18/14

          # 12/8

  - width: 1/3
    fields:
      cover:
        headline: Capa
        type: files
        template: cover
        multiple: false
        required: true
      categories:
        label: Categorias
        type: checkboxes
        width: 1/3
        min: 1
        max: 3
        options:
          package: Design de embalagem
          book: Design de livro
          visualid: Identidade visual
          illustration: Ilustração
          lettering: Lettering
          mural: Pintura de mural
          personal: Projeto pessoal
      text:
        label: Texto
        type: textarea
        width: 1/3
        size: small
        required: true