title: Site

columns:
  - width: 1/2
    sections:
      gallery: sections/gallery

  - width: 1/2
    sections:
      pages:
        type: pages
        status: listed
        image:
            back: white
